export interface SongEntry { artist: string; title: string }

export const DECADE_SONGS: Record<string, SongEntry[]> = {
  '60s': [
    { artist: 'The Beatles', title: 'Hey Jude' },
    { artist: 'The Beatles', title: 'Let It Be' },
    { artist: 'The Beatles', title: 'Come Together' },
    { artist: 'The Beatles', title: 'I Want to Hold Your Hand' },
    { artist: 'The Rolling Stones', title: 'Satisfaction' },
    { artist: 'The Beach Boys', title: 'Good Vibrations' },
    { artist: 'Aretha Franklin', title: 'Respect' },
    { artist: 'Bob Dylan', title: 'Like a Rolling Stone' },
    { artist: 'The Doors', title: 'Light My Fire' },
    { artist: 'Elvis Presley', title: "Can't Help Falling in Love" },
    { artist: 'The Supremes', title: "You Can't Hurry Love" },
    { artist: 'The Supremes', title: 'Stop In The Name Of Love' },
    { artist: 'Marvin Gaye', title: 'I Heard It Through the Grapevine' },
    { artist: 'Otis Redding', title: 'Sittin On The Dock of the Bay' },
    { artist: 'The Kinks', title: 'You Really Got Me' },
    { artist: 'The Animals', title: 'House of the Rising Sun' },
    { artist: 'The Byrds', title: 'Mr. Tambourine Man' },
    { artist: 'Simon & Garfunkel', title: 'The Sound of Silence' },
    { artist: 'Simon & Garfunkel', title: 'Mrs. Robinson' },
    { artist: 'Jimi Hendrix', title: 'Purple Haze' },
    { artist: 'Jimi Hendrix', title: 'All Along the Watchtower' },
    { artist: 'Cream', title: 'Sunshine of Your Love' },
    { artist: 'The Who', title: 'My Generation' },
    { artist: 'The Who', title: 'Pinball Wizard' },
    { artist: 'Janis Joplin', title: 'Piece of My Heart' },
    { artist: 'The Mamas & The Papas', title: 'California Dreamin' },
    { artist: 'The Righteous Brothers', title: 'Unchained Melody' },
    { artist: 'Roy Orbison', title: 'Oh, Pretty Woman' },
    { artist: 'The Temptations', title: 'My Girl' },
    { artist: 'Wilson Pickett', title: 'Mustang Sally' },
    { artist: 'James Brown', title: 'I Feel Good' },
    { artist: 'Frank Sinatra', title: 'Strangers in the Night' },
    { artist: 'Nancy Sinatra', title: 'These Boots Are Made for Walkin' },
    { artist: 'The Monkees', title: "I'm a Believer" },
    { artist: 'The Zombies', title: 'Time of the Season' },
    { artist: 'The Hollies', title: 'Bus Stop' },
    { artist: 'Jefferson Airplane', title: 'Somebody to Love' },
    { artist: 'Jefferson Airplane', title: 'White Rabbit' },
    { artist: 'Buffalo Springfield', title: 'For What Its Worth' },
    { artist: 'The Turtles', title: 'Happy Together' },
    { artist: 'Steppenwolf', title: 'Born to Be Wild' },
    { artist: 'Procol Harum', title: 'A Whiter Shade of Pale' },
    { artist: 'The Troggs', title: 'Wild Thing' },
    { artist: 'Donovan', title: 'Sunshine Superman' },
    { artist: 'Sam Cooke', title: 'Wonderful World' },
    { artist: 'Sam Cooke', title: 'A Change Is Gonna Come' },
    { artist: 'Percy Sledge', title: 'When a Man Loves a Woman' },
    { artist: 'Dusty Springfield', title: 'Son of a Preacher Man' },
    { artist: 'Petula Clark', title: 'Downtown' },
    { artist: 'Tom Jones', title: "It's Not Unusual" },
    { artist: 'The Foundations', title: 'Build Me Up Buttercup' },
    { artist: 'The Ronettes', title: 'Be My Baby' },
    { artist: 'The Shangri-Las', title: 'Leader of the Pack' },
    { artist: 'Dion', title: 'Runaround Sue' },
    { artist: 'Del Shannon', title: 'Runaway' },
    { artist: 'Chubby Checker', title: 'The Twist' },
    { artist: 'Ben E. King', title: 'Stand by Me' },
    { artist: 'Etta James', title: 'At Last' },
    { artist: 'Bobby Darin', title: 'Beyond the Sea' },
    { artist: 'Manfred Mann', title: 'Do Wah Diddy Diddy' },
    { artist: 'Small Faces', title: 'Itchycoo Park' },
    { artist: 'The Moody Blues', title: 'Nights in White Satin' },
    { artist: 'The Band', title: 'The Weight' },
    { artist: 'Sly & The Family Stone', title: 'Everyday People' },
    { artist: 'Creedence Clearwater Revival', title: 'Proud Mary' },
    { artist: 'Creedence Clearwater Revival', title: 'Bad Moon Rising' },
    { artist: 'Creedence Clearwater Revival', title: 'Fortunate Son' },
    { artist: 'Neil Diamond', title: 'Sweet Caroline' },
    { artist: 'Johnny Cash', title: 'Ring of Fire' },
    { artist: 'Johnny Cash', title: 'Folsom Prison Blues' },
    { artist: 'The Everly Brothers', title: "Cathy's Clown" },
    { artist: 'Don McLean', title: 'American Pie' },
  ],

  '70s': [
    { artist: 'Led Zeppelin', title: 'Stairway to Heaven' },
    { artist: 'Queen', title: 'Bohemian Rhapsody' },
    { artist: 'Eagles', title: 'Hotel California' },
    { artist: 'Bee Gees', title: "Stayin' Alive" },
    { artist: 'Elton John', title: 'Your Song' },
    { artist: 'Stevie Wonder', title: 'Superstition' },
    { artist: 'ABBA', title: 'Dancing Queen' },
    { artist: 'Pink Floyd', title: 'Another Brick in the Wall' },
    { artist: 'Fleetwood Mac', title: 'Go Your Own Way' },
    { artist: 'John Lennon', title: 'Imagine' },
    { artist: 'David Bowie', title: 'Heroes' },
    { artist: 'David Bowie', title: 'Space Oddity' },
    { artist: 'The Clash', title: 'London Calling' },
    { artist: 'The Ramones', title: 'Blitzkrieg Bop' },
    { artist: 'Bruce Springsteen', title: 'Born to Run' },
    { artist: 'Billy Joel', title: 'Piano Man' },
    { artist: 'The Rolling Stones', title: 'Angie' },
    { artist: 'The Who', title: "Baba O'Riley" },
    { artist: 'Deep Purple', title: 'Smoke on the Water' },
    { artist: 'Black Sabbath', title: 'Paranoid' },
    { artist: 'Aerosmith', title: 'Dream On' },
    { artist: 'Lynyrd Skynyrd', title: 'Sweet Home Alabama' },
    { artist: 'Bob Marley', title: 'No Woman, No Cry' },
    { artist: 'Bob Marley', title: 'Three Little Birds' },
    { artist: 'Marvin Gaye', title: "What's Going On" },
    { artist: 'Al Green', title: "Let's Stay Together" },
    { artist: 'Earth, Wind & Fire', title: 'September' },
    { artist: 'Donna Summer', title: 'I Feel Love' },
    { artist: 'Gloria Gaynor', title: 'I Will Survive' },
    { artist: 'Village People', title: 'YMCA' },
    { artist: 'Michael Jackson', title: "Don't Stop 'Til You Get Enough" },
    { artist: 'Carole King', title: "It's Too Late" },
    { artist: 'James Taylor', title: 'Fire and Rain' },
    { artist: 'Carly Simon', title: "You're So Vain" },
    { artist: 'Joni Mitchell', title: 'Big Yellow Taxi' },
    { artist: 'Simon & Garfunkel', title: 'Bridge Over Troubled Water' },
    { artist: 'Harry Nilsson', title: 'Without You' },
    { artist: 'Rod Stewart', title: 'Maggie May' },
    { artist: 'George Harrison', title: 'My Sweet Lord' },
    { artist: 'America', title: 'A Horse with No Name' },
    { artist: 'Electric Light Orchestra', title: 'Mr. Blue Sky' },
    { artist: 'Supertramp', title: 'The Logical Song' },
    { artist: 'Hall & Oates', title: 'Rich Girl' },
    { artist: 'AC/DC', title: 'Highway to Hell' },
    { artist: 'Thin Lizzy', title: 'The Boys Are Back in Town' },
    { artist: 'Boston', title: 'More Than a Feeling' },
    { artist: 'Foreigner', title: 'Cold as Ice' },
    { artist: 'Meat Loaf', title: 'Bat Out of Hell' },
    { artist: 'Blondie', title: 'Heart of Glass' },
    { artist: 'Talking Heads', title: 'Psycho Killer' },
    { artist: 'T. Rex', title: 'Get It On' },
    { artist: 'Sweet', title: 'Ballroom Blitz' },
    { artist: 'The Cars', title: 'Just What I Needed' },
    { artist: 'Dire Straits', title: 'Sultans of Swing' },
    { artist: 'Van Morrison', title: 'Moondance' },
    { artist: 'Van Morrison', title: 'Brown Eyed Girl' },
    { artist: 'Neil Young', title: 'Heart of Gold' },
    { artist: 'The Allman Brothers Band', title: "Ramblin' Man" },
    { artist: 'Santana', title: 'Black Magic Woman' },
    { artist: 'War', title: 'Low Rider' },
    { artist: 'Barry White', title: "You're the First, the Last, My Everything" },
    { artist: 'Roberta Flack', title: 'Killing Me Softly with His Song' },
    { artist: 'Olivia Newton-John', title: 'Hopelessly Devoted to You' },
    { artist: 'John Denver', title: 'Take Me Home, Country Roads' },
    { artist: 'Jim Croce', title: 'Time in a Bottle' },
    { artist: 'Don McLean', title: 'American Pie' },
    { artist: 'Curtis Mayfield', title: 'Move On Up' },
    { artist: 'KC and the Sunshine Band', title: "That's the Way I Like It" },
    { artist: 'The Jackson 5', title: 'ABC' },
    { artist: 'Chicago', title: 'If You Leave Me Now' },
    { artist: 'Bread', title: 'Make It with You' },
  ],

  '80s': [
    { artist: 'Michael Jackson', title: 'Billie Jean' },
    { artist: 'Michael Jackson', title: 'Beat It' },
    { artist: 'Madonna', title: 'Like a Virgin' },
    { artist: 'Madonna', title: 'Material Girl' },
    { artist: 'Prince', title: 'Purple Rain' },
    { artist: 'Prince', title: 'When Doves Cry' },
    { artist: 'Whitney Houston', title: 'I Wanna Dance with Somebody' },
    { artist: 'Bon Jovi', title: "Livin' on a Prayer" },
    { artist: 'Journey', title: "Don't Stop Believin'" },
    { artist: 'A-ha', title: 'Take On Me' },
    { artist: 'U2', title: 'With or Without You' },
    { artist: 'U2', title: 'Sunday Bloody Sunday' },
    { artist: 'Cyndi Lauper', title: 'Girls Just Want to Have Fun' },
    { artist: "Guns N' Roses", title: "Sweet Child O' Mine" },
    { artist: 'AC/DC', title: 'Back in Black' },
    { artist: 'Queen', title: 'Another One Bites the Dust' },
    { artist: 'The Police', title: 'Every Breath You Take' },
    { artist: 'The Police', title: 'Roxanne' },
    { artist: 'Bruce Springsteen', title: 'Born in the U.S.A.' },
    { artist: 'Bruce Springsteen', title: 'Dancing in the Dark' },
    { artist: 'George Michael', title: 'Careless Whisper' },
    { artist: 'Wham!', title: 'Wake Me Up Before You Go-Go' },
    { artist: 'Duran Duran', title: 'Hungry Like the Wolf' },
    { artist: 'Duran Duran', title: 'Rio' },
    { artist: 'Depeche Mode', title: "Just Can't Get Enough" },
    { artist: 'The Cure', title: 'Just Like Heaven' },
    { artist: 'The Smiths', title: 'This Charming Man' },
    { artist: 'New Order', title: 'Blue Monday' },
    { artist: 'Talking Heads', title: 'Once in a Lifetime' },
    { artist: 'Blondie', title: 'Call Me' },
    { artist: 'Billy Joel', title: 'Uptown Girl' },
    { artist: 'Phil Collins', title: 'In the Air Tonight' },
    { artist: 'Genesis', title: 'Invisible Touch' },
    { artist: 'Peter Gabriel', title: 'Sledgehammer' },
    { artist: 'David Bowie', title: "Let's Dance" },
    { artist: 'Eurythmics', title: 'Sweet Dreams Are Made of This' },
    { artist: 'Tears for Fears', title: 'Everybody Wants to Rule the World' },
    { artist: 'Simple Minds', title: "Don't You Forget About Me" },
    { artist: 'Aerosmith', title: 'Walk This Way' },
    { artist: 'Run-D.M.C.', title: "It's Tricky" },
    { artist: 'Public Enemy', title: 'Fight the Power' },
    { artist: 'N.W.A', title: 'Straight Outta Compton' },
    { artist: 'Salt-N-Pepa', title: 'Push It' },
    { artist: 'Beastie Boys', title: 'Fight for Your Right' },
    { artist: 'LL Cool J', title: 'I Need Love' },
    { artist: 'Janet Jackson', title: 'Rhythm Nation' },
    { artist: 'Tina Turner', title: "What's Love Got to Do with It" },
    { artist: 'Lionel Richie', title: 'All Night Long' },
    { artist: 'Kenny Loggins', title: 'Footloose' },
    { artist: 'Survivor', title: 'Eye of the Tiger' },
    { artist: 'Europe', title: 'The Final Countdown' },
    { artist: 'Rick Astley', title: 'Never Gonna Give You Up' },
    { artist: 'Bonnie Tyler', title: 'Total Eclipse of the Heart' },
    { artist: 'Bryan Adams', title: "Summer of '69" },
    { artist: 'Pat Benatar', title: 'Love Is a Battlefield' },
    { artist: 'Joan Jett', title: "I Love Rock 'n Roll" },
    { artist: 'Def Leppard', title: 'Pour Some Sugar on Me' },
    { artist: 'Poison', title: 'Every Rose Has Its Thorn' },
    { artist: 'Motley Crue', title: 'Girls, Girls, Girls' },
    { artist: 'Van Halen', title: 'Jump' },
    { artist: 'ZZ Top', title: 'Sharp Dressed Man' },
    { artist: 'Dire Straits', title: 'Money for Nothing' },
    { artist: 'Paul Simon', title: 'You Can Call Me Al' },
    { artist: 'Hall & Oates', title: 'Maneater' },
    { artist: 'The Human League', title: "Don't You Want Me" },
    { artist: 'Soft Cell', title: 'Tainted Love' },
    { artist: 'Culture Club', title: 'Karma Chameleon' },
    { artist: 'Dead or Alive', title: 'You Spin Me Round' },
    { artist: 'Bananarama', title: 'Venus' },
    { artist: 'Kylie Minogue', title: 'I Should Be So Lucky' },
    { artist: 'Pet Shop Boys', title: 'West End Girls' },
    { artist: 'Erasure', title: 'A Little Respect' },
    { artist: 'A Flock of Seagulls', title: 'I Ran' },
    { artist: 'Men at Work', title: 'Down Under' },
    { artist: 'Midnight Oil', title: 'Beds Are Burning' },
    { artist: 'INXS', title: 'Need You Tonight' },
    { artist: 'Crowded House', title: "Don't Dream It's Over" },
    { artist: 'The Bangles', title: 'Walk Like an Egyptian' },
  ],

  '90s': [
    { artist: 'Nirvana', title: 'Smells Like Teen Spirit' },
    { artist: 'Britney Spears', title: 'Baby One More Time' },
    { artist: 'TLC', title: 'No Scrubs' },
    { artist: 'Whitney Houston', title: 'I Will Always Love You' },
    { artist: 'Oasis', title: 'Wonderwall' },
    { artist: 'Backstreet Boys', title: 'I Want It That Way' },
    { artist: 'Spice Girls', title: 'Wannabe' },
    { artist: 'R.E.M.', title: 'Losing My Religion' },
    { artist: 'Radiohead', title: 'Creep' },
    { artist: 'Pearl Jam', title: 'Alive' },
    { artist: 'Soundgarden', title: 'Black Hole Sun' },
    { artist: 'Alice in Chains', title: 'Man in the Box' },
    { artist: 'Red Hot Chili Peppers', title: 'Under the Bridge' },
    { artist: 'Green Day', title: 'Basket Case' },
    { artist: 'The Offspring', title: 'Self Esteem' },
    { artist: 'Blink-182', title: 'All the Small Things' },
    { artist: 'Foo Fighters', title: 'Everlong' },
    { artist: 'Metallica', title: 'Enter Sandman' },
    { artist: "Guns N' Roses", title: 'November Rain' },
    { artist: 'U2', title: 'One' },
    { artist: 'The Cranberries', title: 'Zombie' },
    { artist: 'Blur', title: 'Song 2' },
    { artist: 'Pulp', title: 'Common People' },
    { artist: 'The Verve', title: 'Bitter Sweet Symphony' },
    { artist: 'Massive Attack', title: 'Teardrop' },
    { artist: 'Daft Punk', title: 'Around the World' },
    { artist: 'The Prodigy', title: 'Firestarter' },
    { artist: 'Fatboy Slim', title: 'Praise You' },
    { artist: 'Beck', title: 'Loser' },
    { artist: 'Alanis Morissette', title: 'You Oughta Know' },
    { artist: 'Sheryl Crow', title: 'All I Wanna Do' },
    { artist: 'No Doubt', title: "Don't Speak" },
    { artist: 'Garbage', title: 'Stupid Girl' },
    { artist: 'Lauryn Hill', title: 'Doo Wop That Thing' },
    { artist: 'Mariah Carey', title: 'Fantasy' },
    { artist: 'Celine Dion', title: 'My Heart Will Go On' },
    { artist: 'Boyz II Men', title: 'End of the Road' },
    { artist: 'Destiny\'s Child', title: 'Say My Name' },
    { artist: 'Jay-Z', title: 'Hard Knock Life' },
    { artist: 'The Notorious B.I.G.', title: 'Juicy' },
    { artist: '2Pac', title: 'California Love' },
    { artist: 'Snoop Dogg', title: 'Gin and Juice' },
    { artist: 'Missy Elliott', title: 'Get Ur Freak On' },
    { artist: 'Will Smith', title: 'Gettin Jiggy Wit It' },
    { artist: 'MC Hammer', title: "U Can't Touch This" },
    { artist: 'Ace of Base', title: 'The Sign' },
    { artist: 'Haddaway', title: 'What Is Love' },
    { artist: 'Snap!', title: 'Rhythm Is a Dancer' },
    { artist: 'Eiffel 65', title: 'Blue Da Ba Dee' },
    { artist: 'Ricky Martin', title: 'Livin la Vida Loca' },
    { artist: 'Jennifer Lopez', title: 'If You Had My Love' },
    { artist: 'Cher', title: 'Believe' },
    { artist: 'Madonna', title: 'Vogue' },
    { artist: 'George Michael', title: 'Freedom 90' },
    { artist: 'Seal', title: 'Kiss from a Rose' },
    { artist: 'Bryan Adams', title: 'Everything I Do I Do It for You' },
    { artist: 'Roxette', title: 'It Must Have Been Love' },
    { artist: 'The Goo Goo Dolls', title: 'Iris' },
    { artist: 'Counting Crows', title: 'Mr. Jones' },
    { artist: 'Matchbox Twenty', title: '3AM' },
    { artist: 'Dr. Dre', title: 'Still DRE' },
    { artist: 'Nas', title: 'NY State of Mind' },
    { artist: 'Aaliyah', title: 'Are You That Somebody' },
    { artist: 'Busta Rhymes', title: 'Woo Hah' },
    { artist: 'Portishead', title: 'Glory Box' },
    { artist: 'Moby', title: 'Porcelain' },
    { artist: 'Fiona Apple', title: 'Criminal' },
    { artist: 'Brandy', title: 'The Boy Is Mine' },
    { artist: 'TLC', title: 'Waterfalls' },
    { artist: 'En Vogue', title: 'Don\'t Let Go Love' },
  ],

  '00s': [
    { artist: 'Beyoncé', title: 'Crazy in Love' },
    { artist: 'Eminem', title: 'Lose Yourself' },
    { artist: 'OutKast', title: 'Hey Ya!' },
    { artist: 'Coldplay', title: 'Viva La Vida' },
    { artist: 'Rihanna', title: 'Umbrella' },
    { artist: 'Usher', title: 'Yeah!' },
    { artist: 'The Killers', title: 'Mr. Brightside' },
    { artist: 'Green Day', title: 'Boulevard of Broken Dreams' },
    { artist: 'Justin Timberlake', title: 'Cry Me a River' },
    { artist: 'Lady Gaga', title: 'Poker Face' },
    { artist: 'Kanye West', title: 'Gold Digger' },
    { artist: 'Jay-Z', title: '99 Problems' },
    { artist: '50 Cent', title: 'In Da Club' },
    { artist: 'Alicia Keys', title: 'Fallin' },
    { artist: 'Amy Winehouse', title: 'Rehab' },
    { artist: 'Britney Spears', title: 'Toxic' },
    { artist: 'Christina Aguilera', title: 'Beautiful' },
    { artist: 'Shakira', title: "Hips Don't Lie" },
    { artist: 'Nelly', title: 'Hot in Herre' },
    { artist: 'Missy Elliott', title: 'Work It' },
    { artist: 'Black Eyed Peas', title: 'I Gotta Feeling' },
    { artist: 'Linkin Park', title: 'In the End' },
    { artist: 'Evanescence', title: 'Bring Me to Life' },
    { artist: 'System of a Down', title: 'Chop Suey' },
    { artist: 'Fall Out Boy', title: 'Sugar We\'re Goin Down' },
    { artist: 'Paramore', title: 'Misery Business' },
    { artist: 'My Chemical Romance', title: 'Welcome to the Black Parade' },
    { artist: 'Arctic Monkeys', title: 'I Bet You Look Good on the Dancefloor' },
    { artist: 'Franz Ferdinand', title: 'Take Me Out' },
    { artist: 'The White Stripes', title: 'Seven Nation Army' },
    { artist: 'The Strokes', title: 'Last Nite' },
    { artist: 'Kings of Leon', title: 'Sex on Fire' },
    { artist: 'MGMT', title: 'Kids' },
    { artist: 'Gorillaz', title: 'Feel Good Inc.' },
    { artist: 'Daft Punk', title: 'One More Time' },
    { artist: 'R. Kelly', title: 'Ignition Remix' },
    { artist: 'Kelly Clarkson', title: 'Since U Been Gone' },
    { artist: 'Avril Lavigne', title: 'Sk8er Boi' },
    { artist: 'Pink', title: 'Get the Party Started' },
    { artist: 'Vanessa Carlton', title: 'A Thousand Miles' },
    { artist: 'Norah Jones', title: "Don't Know Why" },
    { artist: 'Jason Mraz', title: "I'm Yours" },
    { artist: 'James Blunt', title: "You're Beautiful" },
    { artist: 'Snow Patrol', title: 'Chasing Cars' },
    { artist: 'Keane', title: 'Somewhere Only We Know' },
    { artist: 'The Fray', title: 'How to Save a Life' },
    { artist: 'Dido', title: 'White Flag' },
    { artist: 'Train', title: 'Drops of Jupiter' },
    { artist: 'Maroon 5', title: 'This Love' },
    { artist: 'OneRepublic', title: 'Apologize' },
    { artist: 'Leona Lewis', title: 'Bleeding Love' },
    { artist: 'Westlife', title: 'Flying Without Wings' },
    { artist: 'NSYNC', title: 'Bye Bye Bye' },
    { artist: 'Backstreet Boys', title: 'Shape of My Heart' },
    { artist: 'Sean Paul', title: 'Get Busy' },
    { artist: 'Daddy Yankee', title: 'Gasolina' },
    { artist: 'Timbaland', title: 'The Way I Are' },
    { artist: 'Akon', title: 'Smack That' },
    { artist: 'Ne-Yo', title: 'So Sick' },
    { artist: 'Blink-182', title: 'I Miss You' },
    { artist: 'David Guetta', title: 'When Love Takes Over' },
    { artist: 'Calvin Harris', title: "I'm Not Alone" },
    { artist: 'John Mayer', title: 'Your Body Is a Wonderland' },
    { artist: 'Nelly Furtado', title: 'Maneater' },
    { artist: 'Justin Timberlake', title: 'SexyBack' },
    { artist: 'Kanye West', title: 'Stronger' },
    { artist: 'Rihanna', title: 'We Found Love' },
    { artist: 'Beyoncé', title: 'Irreplaceable' },
    { artist: 'Eminem', title: 'Without Me' },
    { artist: 'Coldplay', title: 'The Scientist' },
    { artist: 'Coldplay', title: 'Yellow' },
  ],
}
